
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  username: <%=  ENV['APP_DATABASE_USERNAME'] %>
  password: <%=  ENV['APP_DATABASE_PASSWORD'] %>
  host: <%=  ENV['APP_DATABASE_HOST'] %>
  database: <%=  ENV['APP_DATABASE_NAME_DEV'] %>

test:
  <<: *default
  username: <%=  ENV['APP_DATABASE_USERNAME'] %>
  password: <%=  ENV['APP_DATABASE_PASSWORD'] %>
  host: <%=  ENV['APP_DATABASE_HOST'] %>
  database: <%=  ENV['APP_DATABASE_NAME_TEST'] %>

production:
  <<: *default
  username: <%=  ENV['APP_DATABASE_USERNAME'] %>
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  host: <%=  ENV['APP_DATABASE_HOST'] %>
  database: <%=  ENV['APP_DATABASE_NAME_PRODUCTION'] %>